baseURL: "https://sbtco.sa/"
theme: "up-business-theme"
languageCode: "en-us"

title: "SBTCO"

googleAnalytics: "G-XEFG7HRRKX"

summaryLength: 20

params:
  title: "SBTCO"
  description: "We specialize in providing services to automate smart buildings using the latest technologies."
  
  images: 
    - "logo/SBTCO LOGO 2a-01.png"

  logo: "logo/SBTCO LOGO 3a-01.png"

  favicons:
    themeColor: "#CD992B"
    backgroundColor: "#F9F7ED"
    faviconColor: "#CD992B"

  social:
    twitter: "https://twitter.com/sbtco_sa"

  location:
    - "Riyadh, Saudi Arabia"
    - "CR: 7037941346"

  contact:
    - "info@sbtco.sa"

  copyright: "© 2022 SBTCO. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About us"
      url: "/about-us"
      weight: 2

    - name: "How we work"
      url: "/how-we-work"
      weight: 3

    - name: "Contact the team"
      url: "/contact-the-team"
      weight: 4

  buttons:
    - name: "CONTACT THE TEAM"
      url: "/contact-us"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "How we work"
      url: "/how-we-work"
      weight: 2

    - name: "Contact us"
      url: "/contact-us"
      weight: 3
