baseURL: "https://sbtco.sa/"
theme: "up-business-theme"
languageCode: "en-us"

title: "SBTCO"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "SBTCO"
  description: "We specialize in providing services to automate smart buildings using the latest technologies."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#CD992B"
    backgroundColor: "#F9F7ED"
    faviconColor: "#CD992B"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "info@sbtco.sa"
    - "207.555.0119"

  copyright: "© 2022 SBTCO. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
